### ISSUE TITLE
Exception when running with `load_keys`

### ISSUE THREAD

**Issue by jkav77** [narger-ef/LowMemoryFHEResNet20#11]
Hello,

I'm very interested in your approach and am digging into the implementation details. However, when I try to run the executable I get an exception.

```
libc++abi: terminating due to uncaught exception of type lbcrypto::OpenFHEException: /Users/dangerginger/code/openfhe-development/src/core/include/lattice/hal/default/dcrtpoly-impl.h:l.698:DropLastElement(): DropLastElement: Removing last element of DCRTPoly renders it invalid.
```

I have followed the instructions on the README with the commands:
```bash
./LowMemoryFHEResNet20 generate_keys 1  
./LowMemoryFHEResNet20 load_keys 1 
```

I've gotten the same results on macOS and Ubuntu linux. In both cases I was using the `openfhe-development` repo. I will try running this in the debugger, but any insight into why this might be happening? This error seems to indicate the multiplicative depth has been exceeded, but I'm not sure about that.

Thanks and I appreciate any hints.

**Comment by narger-ef** [comment]
Hello, thank you for the question!

Could you please try to:

- Use OpenFHE v1.0.4
OR
- Set `parameters.SetSecurityLevel(SecurityLevel::HEStd_NotSet);` and change line 123 of FHEController.cpp to uint32_t levelsUsedBeforeBootstrap = get_relu_depth(relu_deg) + 4;

Notice that the latter does not ensure $\lambda = 128$ security bits

**Comment by minnow54426** [comment]
Hello, you can refer to https://github.com/narger-ef/LowMemoryFHEResNet20/issues/9 for more details.

**Comment by narger-ef** [comment]
I am closing the issue, feel free to open if you still have issues
