### ISSUE TITLE
Operational issues

### ISSUE THREAD

**Issue by dz12123** [narger-ef/LowMemoryFHEResNet20#15]
![image](https://github.com/narger-ef/LowMemoryFHEResNet20/assets/101967519/c2bb115e-7cad-4929-8741-d2215665f9d9)
How to solve the error in the second step of running the project according to the Readme file?

/LowMemoryFHEResNet20-main# cmake -B "build" -S LowMemoryFHEResNet20
CMake Error: The source directory "/root/LowMemoryFHEResNet20-main/LowMemoryFHEResNet20" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by narger-ef** [comment]
Try to launch 
`
cmake -S . build
`

in the root folder, does it work?

**Comment by narger-ef** [comment]
@dz12123 please let me know whether you were able to fix the issue, otherwise I will close it :) Thanks!
