### ISSUE TITLE
Is it feasible to generate a RotateKeyGen without specifying EvalBootstrapSetup({4, 4}, {0, 0}, 16384)?

### ISSUE THREAD

**Issue by yellow123Nike** [narger-ef/LowMemoryFHEResNet20#16]
![image](https://github.com/narger-ef/LowMemoryFHEResNet20/assets/37546857/d073b6f5-d68a-4add-b662-7426229f610d)
Is it feasible to generate a RotateKeyGen without specifying EvalBootstrapSetup({4, 4}, {0, 0}, 16384)?

**Comment by yellow123Nike** [comment]
![image](https://github.com/narger-ef/LowMemoryFHEResNet20/assets/37546857/f6440502-1b62-4e3b-8f40-dca3f8d12b5e)
![image](https://github.com/narger-ef/LowMemoryFHEResNet20/assets/37546857/2018366b-29d1-494b-9962-55d183ad2ff8)
![image](https://github.com/narger-ef/LowMemoryFHEResNet20/assets/37546857/bf8b83e8-32fb-4600-927a-f2beb15f729d)
However, the following error occurred at `res = m_cc->EvalAdd(res, m_cc->EvalRotate(sum, 1024));`.

**Comment by narger-ef** [comment]
This happens because $1024 \neq -1024$. I think that the actual rotation for $-1024$ is $16384-1024=15360$

**Comment by yellow123Nike** [comment]
However, after adding `context->EvalBootstrapSetup({4, 4}, {0, 0}, 16384);`, this issue did not occur. Apologies, I am a beginner in FHE.

**Comment by narger-ef** [comment]
No worries, I am still learning, too :-P.

The bootstrapping its self uses a lot of rotation keys, perhaps that setup generates the key also for $15360$. 

To confirm, check the memory when you 
- generate the bootstrapping keys
vs
- generate the bootstrapping keys + rotation keys 15360. 


If they are the same, then the rotation key for $15360$ is already included in the ones used by the bootstrapping

**Comment by yellow123Nike** [comment]
Thank you very much!

**Comment by narger-ef** [comment]
Feel free to re-open if you have issues :)

**Comment by yellow123Nike** [comment]
![image](https://github.com/narger-ef/LowMemoryFHEResNet20/assets/37546857/fdf38c56-78b3-4c62-a7f2-9c747adf9892)
![image](https://github.com/narger-ef/LowMemoryFHEResNet20/assets/37546857/24122313-a568-4c24-97e9-11b62ecced55)
Why is the error from layer 3 to FC so large?
