### ISSUE TITLE
Can you provide a docker image, or how to install an older version of OpenFHE ?

### ISSUE THREAD

**Issue by Sinking-Stone** [narger-ef/LowMemoryFHEResNet20#18]
Hello, I read your paper and was very interested in your work, but when I installed the old version 1.0.4, I found that I couldn't install it correctly.
When I tried to install the older version, after I downloaded 1.0.4 and downloaded all the dependent repositories in the third-party directory, I got the following error after executing make -j4. 
![338420671-377f7dc0-7020-40dd-9c28-db88aa14b792](https://github.com/narger-ef/LowMemoryFHEResNet20/assets/89176650/b83335eb-dfe6-42cc-b0c1-899b12adff76)
When I commented out the error there was a new error.
![338422573-c27b1c84-a022-42ee-84e8-a5de640fba68](https://github.com/narger-ef/LowMemoryFHEResNet20/assets/89176650/8422faac-ee55-46c3-974c-3eff2b146b32)
My OS is 20.04.1-Ubuntu, and I have installed all the required environment dependencies.

**Comment by narger-ef** [comment]
Uhhm.. I honestly does not know how to use docker, in case you are just playing around with the library, I suggest you to simply relax the security level to use it without issues in the newer versions.

In 1.0.4 it seems that bootstrapping was consuming one less level, this is why on newer versions the circuit is not considered secure anymore by the library

**Comment by Sinking-Stone** [comment]
Thank you for your reply, I looked at the method in #11  can really solve my problem. But I still want to know, how can I make 128bit safe without changing the `parameters.SetSecurityLevel(SecurityLevel::HEStd_NotSet)` and `generate_context` from 16 to 17.

**Comment by narger-ef** [comment]
If you go from 16 to 17 and you let security level to 128 bits, it will work

**Comment by Sinking-Stone** [comment]
Yes, I have just tried it, it will have a large memory footprint, so is there one that can guarantee the safety of 128bits without changing the N size.

**Comment by narger-ef** [comment]
Feel free to close the issue if resolved :)

**Comment by Sinking-Stone** [comment]
Hello, I'm very sorry to bother you again. When I read your source code, I don't quite understand how your downsampling is calculated. Could you explain it to me, because it is just a simple description in your paper.
