### ISSUE TITLE
The time is much longer

### ISSUE THREAD

**Issue by Lucas-Wye** [narger-ef/LowMemoryFHEResNet20#19]
Here is the running time on Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz, which is about 2x longer.
Is there any settings I need  to do?

![image](https://github.com/narger-ef/LowMemoryFHEResNet20/assets/30680577/a104e566-9007-42f6-9e12-7f8c6d9a98b3)

**Comment by narger-ef** [comment]
That's hard to judge, my times were reported from a MacBook 2021 M1 Pro.

What parameters are you using? How much ram do you have? Is the SSD fast?

**Comment by narger-ef** [comment]
Feel free to re-open when you have more information
