### ISSUE TITLE
Encouter Exception "what():  DropLastElement: Removing last element of DCRTPoly renders it invalid." during runtime.

### ISSUE THREAD

**Issue by JerryFishY** [narger-ef/LowMemoryFHEResNet20#9]
I encoutered an error during runtime.

The version of OpenFHE I am using is v1.1.3,

the command I execute is: 

``` shell
./LowMemoryFHEResNet20 generate_keys 1

./LowMemoryFHEResNet20 load_keys 1 input "inputs/vale.jpg"
```
The first command runs successfully while the second one will encouter an exception: 

``` shell
Encrypted ResNet20 classification started.
I am going to encrypt and classify ../inputs/vale.jpg.
terminate called after throwing an instance of 'lbcrypto::OpenFHEException'
  what():  DropLastElement: Removing last element of DCRTPoly renders it invalid.
Aborted (core dumped)
```

**Comment by narger-ef** [comment]
That's weird, I replicated the commands and I obtain:

```
narger@MacBook-Pro-di-Lorenzo build % ./LowMemoryFHEResNet20 generate_keys 1

Ciphertexts depth: 23, available multiplications: 7
You are using log(Q+P) = 1756
Context built, generating keys...
Generated.
Now serializing keys ...
EvalMult keys have been serialized
Crypto Context have been serialized
Public Key has been serialized
Secret Key has been serialized
Rotation keys "rotations-layer1.bin" have been serialized
Rotation keys "rotations-layer2-downsample.bin" have been serialized
Rotation keys "rotations-layer2.bin" have been serialized
Rotation keys "rotations-layer3-downsample.bin" have been serialized
Rotation keys "rotations-layer3.bin" have been serialized
Rotation keys "rotations-finallayer.bin" have been serialized
Context created correctly.

narger@MacBook-Pro-di-Lorenzo build % ./LowMemoryFHEResNet20 load_keys 1 input "inputs/vale.jpg"
Encrypted ResNet20 classification started.
I am going to encrypt and classify ../inputs/vale.jpg.
Decrypting the output...
Output: [ -0.384, -2.183, -2.889,  2.112, -1.509,  9.036, -1.412, -1.074, -0.251, -1.438 ]
The input image is classified as Dog
The index of max element is 5
```

That error means that it is trying to reseale a ciphertext at the last level, I guess it is happening before the bootstrapping. I wonder if OpenFHE's last version has something different in that procedure.

Could you please:

- Clear the generated keys in the `keys_exp1` folder
- Change line 123 of `FHEController.cpp` to `uint32_t levelsUsedBeforeBootstrap = get_relu_depth(relu_deg) + 4;`
- Re-execute the code

?

Thank you

**Comment by JerryFishY** [comment]
Sorry for late response, it could now successfully run after changing the levels and ring size. Thanks!

**Comment by yellow123Nike** [comment]
I tried FHEController.cpp to uint32_tlevelsUsedBeforeBootstrap = get_relu_depth(relu_deg) + 4; but error
![image](https://github.com/narger-ef/LowMemoryFHEResNet20/assets/37546857/c7c1b2ab-50aa-4a14-8fcc-6ecb208fab53)
How to set parameters？
![image](https://github.com/narger-ef/LowMemoryFHEResNet20/assets/37546857/94ad7415-1a41-4023-8600-3b2ae754f944)
t'hthanks
